{% set name = "kneed" %}
{% set version = "0.8.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 65b22727c623661701f15edf057f2e6c73e2b1ad4e68cd9ca4291675c318b5ef

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-build-isolation --no-deps -vv

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - numpy >=1.14.2
    - scipy >=1.0.0
test:
  imports:
    - kneed
  requires:
    - pip
  commands:
    - pip check
  
about:
  home: https://github.com/arvkevi/kneed
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Knee point detection using Python
  description: |
    This repository is an attempt to implement the kneedle algorithm. 
    Given a set of x and y values, kneed will return the knee point of the function. 
    The knee point is the point of maximum curvature.
  doc_url: https://kneed.readthedocs.io
  dev_url: https://github.com/arvkevi/kneed

extra:
  recipe-maintainers:
    - arvkevi
