travis:
  secure:
    BINSTAR_TOKEN: re4Lij7JTwy7NDczNEAOM8qNBLMQ/D2+QpThypzU8/1u2/tMU3uecMLt/br1U4mriiRXHFbG4qFJyYqWScDgWoMjnsOlBM5GXHvjgdt9ptMFeFo781y9xSNQ4RV+k1Inc159B+47+sZ/MIyo19aBFRsttjPKRrUOleFeS6ftip3CWVKSybAwfjQgGOdHIkQfQdRnN8xvU4CNWMqNPrssOUUQ/1kJIiVwwVxPiPIFe/VIzYL4rsRntSNEhZBSgXeQY5Uv7yr4tzZbG+ReLWNrv9nrYjt1EdqJIWt4GZJhe47upI0ZGhYa5QTTAu25G3lEMHiYhPE5+bYhn9Q2XqZaL6JlAFIQkcE+XC8BL9X4ewrok4SquotjFk6fZWI586++RPAFTniW02gTPGDy9NZNQ20Y5XdSk4W745EdgMJ0ljzg5HccY1v7XWn/NnE1H17jtawjtU0lAM+G8r29czckUE0RL/MuLJB+5mznfe3A94t2glH18oo9ob2aeADZFOBCMsFq2tt2ZhUSI50JQwjYB47jfxFITKmzY4tNTFxnDwivOkzn+ED3xHSDL+K+kKmEIIiGAkS3nvCtrF6iqMFhiHD45ICxlnHJuoxqkBUhPztNVWBaXbqrA3jHyEqilJN9Z5bWh8sTsU6TPfSw4a2znO6eoTYa8RWE/P8feC1Qoig=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
